spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19991004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 8.135.58.186
    port: 26379
    database: 0
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-idle: 10

logging:
  level:
    root: info
    com.lucifer: debug
  file:
    path: log/blog-dev.log
server:
  port: 8081



#mybatis:
#  mapper-locations:
#    - classpath:/mapper/**.xml